import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { PageHeader } from "@/components/marketing/page-header";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms governing use of the Fresco AI mobile application and related services, provided by XARP.",
};

const SUPPORT_EMAIL = "frescoai@xarp.org";

export default function TermsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Terms of Service"
        title="The terms for using Fresco AI."
        description={
          <>Effective date: July 20, 2026 · Last updated: July 20, 2026</>
        }
      />

      <section className="py-20 sm:py-28">
        <Container className="max-w-3xl">
          <div className="mb-10 rounded-2xl border border-warning-border bg-warning-bg px-6 py-4 text-sm leading-relaxed text-warning">
            <strong>Draft pending counsel review.</strong> This page is a
            working draft of Fresco AI&apos;s Terms of Service. It has not yet
            been reviewed by an attorney and should not be relied on as final
            until legal counsel has approved it.
          </div>

          <div className="prose-legal flex flex-col gap-10 text-base leading-relaxed text-muted-foreground">
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern access to
              and use of the Fresco AI mobile application, admin app, and
              related services (the &ldquo;Service&rdquo;), provided by XARP
              (&ldquo;XARP,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
              &ldquo;our&rdquo;). By creating an account or using the Service,
              you agree to these Terms on behalf of yourself and, where
              applicable, the organization you represent.
            </p>

            <PolicySection number="1" title="The Service">
              <p>
                Fresco AI is a general-purpose Field Service Management (FSM)
                mobile app. A manager, supervisor, or foreman creates a To Do
                List by voice, text, or annotated photo; the Service
                dispatches it to a team member as a text link; the team
                member completes each task with a photo or a spoken reason;
                and the Service returns a verified completion certificate to
                the dispatcher.
              </p>
            </PolicySection>

            <PolicySection number="2" title="Accounts and Roles">
              <p>
                Organizations designate administrators, dispatchers,
                managers, supervisors, and foremen, and invite team members by
                phone number. You are responsible for the accuracy of
                information provided and for activity that occurs under your
                organization&apos;s account.
              </p>
            </PolicySection>

            <PolicySection number="3" title="Acceptable Use">
              <p>You agree not to:</p>
              <ul className="list-disc space-y-2 pl-5">
                <li>Use the Service for any unlawful purpose or to submit false or fraudulent completion certificates</li>
                <li>Attempt to interfere with, disrupt, or reverse-engineer the Service</li>
                <li>Submit content that infringes the rights of a third party</li>
                <li>Use the Service to store or transmit content unrelated to field service management</li>
              </ul>
            </PolicySection>

            <PolicySection number="4" title="Completion Certificates and Third-Party Recipients">
              <p>
                Completion certificates generated by the Service may be
                forwarded by your organization&apos;s dispatcher to clients,
                inspectors, or other third parties. Once a certificate has
                been forwarded outside your organization, XARP is not
                responsible for its further distribution or use.
              </p>
            </PolicySection>

            <PolicySection number="5" title="Fees">
              <p>
                Current plans are described at{" "}
                <a href="/pricing" className="text-primary hover:underline">
                  fresco.xarp.org/pricing
                </a>
                . Fees, if any, are billed to the organization&apos;s account
                on the schedule disclosed at signup or in an order form.
              </p>
            </PolicySection>

            <PolicySection number="6" title="Intellectual Property">
              <p>
                XARP retains all rights, title, and interest in the Service,
                including the deterministic engine, software, and branding.
                Your organization retains rights to the content it submits
                through the Service (voice, text, photos, and completion
                certificates).
              </p>
            </PolicySection>

            <PolicySection number="7" title="Disclaimers and Limitation of Liability">
              <p>
                The Service is provided &ldquo;as is&rdquo; without
                warranties of any kind. To the maximum extent permitted by
                law, XARP is not liable for indirect, incidental, or
                consequential damages arising from use of the Service.
              </p>
            </PolicySection>

            <PolicySection number="8" title="Termination">
              <p>
                Either party may terminate access to the Service in
                accordance with the order form or, absent one, with 30
                days&apos; written notice. XARP may suspend access immediately
                for a violation of Section 3.
              </p>
            </PolicySection>

            <PolicySection number="9" title="Governing Law">
              <p>
                These Terms are governed by the laws of the State of
                California, without regard to conflict-of-laws principles.
              </p>
            </PolicySection>

            <PolicySection number="10" title="Changes to These Terms">
              <p>
                We may update these Terms from time to time. Material changes
                will be posted on this page with an updated effective date.
              </p>
            </PolicySection>

            <PolicySection number="11" title="Contact Us">
              <p>
                Questions about these Terms:
                <br />
                <strong className="text-foreground">XARP</strong>
                <br />
                <a href={`mailto:${SUPPORT_EMAIL}`} className="text-primary hover:underline">
                  {SUPPORT_EMAIL}
                </a>
                <br />
                San Diego, CA
              </p>
            </PolicySection>
          </div>
        </Container>
      </section>
    </>
  );
}

function PolicySection({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-3 border-t border-border pt-8">
      <h2 className="flex items-baseline gap-3 text-xl font-semibold text-foreground">
        <span className="font-mono text-sm font-semibold text-faint-foreground">{number}</span>
        {title}
      </h2>
      <div className="flex flex-col gap-3">{children}</div>
    </div>
  );
}
